### ISSUE TITLE
9anime doesn't work

### ISSUE THREAD

**Issue by iCeY3** [KillerDogeEmpire/Cloudstream#4]
### Source information

9anime

### Source link

9anime.id

### Steps to reproduce

![Screenshot_20220804-160756_CloudStream Beta](https://user-images.githubusercontent.com/98146929/182938785-30a30afc-3416-4e21-a168-4b3cd5444aa1.jpg)

### CloudStream version

Pre (latest)

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by KillerDogeEmpire** [comment]
@iCeY3 I'm currently trying to fix

**Comment by iCeY3** [comment]
Thank you..
Waiting for the fix 🙏🏻

**Comment by KillerDogeEmpire** [comment]
@iCeY3 don't know if I can fix it, 9anime keeps changing their keys daily
